name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::179916804929:role/github-actions-brunograna-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "brunograna-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "brunograna-sa-east-1-terraform-lock"